### PR TITLE
Gradient added

### PR DESCRIPTION
**Pull request by karnikagupta30**
Gradient has been added to make it look attractive and some spellings are corrected.
resolves issue #8

### CODE REVIEW

**Review by Rahilsiddique — CHANGES_REQUESTED** [review]
hey @tokyo3001, you have done a great job of adding the gradient, but here are few things that you can improve on,
1. the text below is also getting the gradient effect but it should 'nt be.
2. try to add the gradeint of color whiteLike to crimson.

**Comment by karnikagupta30** [comment]
> hey @tokyo3001, you have done a great job of adding the gradient, but here are few things that you can improve on,
> 
> 1. the text below is also getting the gradient effect but it should 'nt be.
> 2. try to add the gradeint of color whiteLike to crimson.

gradient of colour whiteLike to crimson needs to be added on the below text or the main heading?

**Comment by karnikagupta30** [comment]
@Rahilsiddique Please review the changes done as per your requirement.

**Comment by Rahilsiddique** [comment]
@tokyo3001 now it seems epic !

**Pull request merged**
